### ISSUE TITLE
L1_RSA_encrypt/L1_RSA_decrypt: avoid sending publ bool to SEcube

### ISSUE THREAD

**Issue by brigio345** [SEcube-Project/SEcube-RSA#3]
L1_RSA_sign => SHA + decrypt
L1_RSA_verify => encrypt + SHA

publ already removed from SEcube side

**Comment by DZipp** [comment]
sign is digest + de
verify is encr + strcmp with digest

publ is removed -> publ encrypt and private decrypt
07d1a8c2df8950d265f45d9b975c14ceaf2cd8b8
